import { readFile, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { build } from 'vite';

// Keep the pasteable Claude Artifact variant reproducible from the Vite source.
// This separate build embeds assets; the deployed site keeps them cacheable.
const result = await build({
  configFile: false,
  publicDir: false,
  build: {
    write: false,
    rolldownOptions: { output: { codeSplitting: false } },
    lib: { entry: resolve('src/app.js'), name: 'RemoteCity', formats: ['iife'] },
  },
});
const script = result[0].output.find(output => output.type === 'chunk').code;
let styles = await readFile('src/site.css', 'utf8');
for (const [match, path] of styles.matchAll(/url\("(\.\/assets\/fonts\/[^"\)]+)"\)/g)) {
  const font = await readFile(resolve('src', path));
  styles = styles.replace(match, 'url("data:font/woff2;base64,' + font.toString('base64') + '")');
}
const html = await readFile('index.html', 'utf8');
const body = html.match(/<body>([\s\S]*?)<\/body>/)[1]
  .replace(/<script type="module"[^>]*><\/script>/, () => '<script>' + script.replaceAll('</script', '<\\/script') + '</script>');
await writeFile('ciudad.html', '<!-- Generated by npm run artifact; edit src/ instead. -->\n'
  + '<title>Ciudad Remote &amp; Partners</title>\n<style>' + styles + '</style>\n' + body.trim() + '\n');
console.log('Generated ciudad.html (standalone, excluded from deployment).');
